services:
  payload:
    image: node:22.23.1-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/pt-payload-poc

  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pt-payload-poc
    volumes:
      - data:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  data:
  node_modules:
